name: Run E2E Tests Manually

on:
  workflow_dispatch: # ← これが手動実行を可能にする
  push: # ← コードがpushされたとき（任意でブランチ指定可）
    branches:
      - main
  pull_request: # ← PRが作成・更新されたとき
    branches:
      - main

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies (root)
        run: npm install

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install && npm run dev &

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install && npm run start &

      - name: Install Playwright dependencies
        run: npx playwright install --with-deps

      - name: un tests
        run: |
          npx wait-on http://localhost:3000/login
          # Run cucumber tests
          npx cucumber-js
          echo "All done."
