name: Run E2E Tests Manually

on:
  workflow_dispatch: # ← これが手動実行を可能にする
  push: # ← コードがpushされたとき（任意でブランチ指定可）
    branches:
      - main
  pull_request: # ← PRが作成・更新されたとき
    branches:
      - main

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies (root)
        run: npm install

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Install Playwright dependencies
        run: npx playwright install --with-deps

      - name: Start server, run test, and kill
        run: |
          cd frontend
          npm run dev &
          cd ../backend
          npm run start &
          SERVER_PID=$!
          npx wait-on http://localhost:4000
          npx cucumber-js
          kill $SERVER_PID
